/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "all": "全部",
    "area(s)": "地区",
    "Capture Rate": "捕获率",
    "story": "故事",
    "Captured": "已捕获",
    "Tooltip here": "工具提示在这里",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Buy": "购买",
    "c/area/s": "捕获/区域/秒",
    "Credit Gain": "积分收益",
    "Credits": "积分",
    "Early-Stage capitalism": "早期资本主义",
    "Late-Stage capitalism": "后期资本主义",
    "Mid-Stage capitalism": "中期资本主义",
    "purchased": "已购买",
    "upgrade": "升级",
    "capitalism": "资本主义",
    "Purchased Early-Stage capitalism": "已购买早期资本主义",
    "Purchased Mid-Stage capitalism": "已购买中期资本主义",
    "Huh... just standing in this area... lets me capture it? It's mine?!": "咦……就站在这片区域……让我拍下来？ 这是我的？！",
    "I feel weird...": "我感觉很奇怪...",
    "It looks like the more I move around and capture areas, the more... Credits... I get?": "看起来我走动越多，捕获的区域就越多……积分……我得到了？",
    "Wait... what are credits? Doesn't matter, I guess. I feel good when they go up!": "等等……什么是积分？ 没关系，我猜。 当他们上升时，我感觉很好！",
    "Where the heck am I?": "我到底在哪里？",
    "\"Scanning\" these ...documents seems to give me some colorful, shiny bits! I don't know what they do but I'm going to keep collecting them!": "“扫描”这些……文件似乎给了我一些色彩斑斓、闪亮的东西！ 我不知道他们在做什么，但我会继续收集它们！",
    "Cheating": "作弊",
    "Column Scan Time": "列扫描时间",
    "Decrease scan time by 0.1s.": "将扫描时间减少 0.1 秒。",
    "Docs": "文档",
    "Docs Scanned": "已扫描的文档",
    "file(s)": "文件",
    "I should scan through these to see if there's anything useful!": "我应该浏览一下这些，看看有没有什么有用的！",
    "Increase scan power by an additional 5%.": "额外增加 5% 的扫描功率。",
    "Instantly scan additional docs (+1 per purchase) when you complete a single scan.": "完成单次扫描后，立即扫描其他文档（每次购买 +1）。",
    "Locked": "未解锁",
    "Multiscan": "多扫描",
    "Need 5x Scanroids, 10x Cheating": "需要 5x Scanroids，10x 作弊",
    "scan": "扫描",
    "Scanning": "扫描",
    "Scanroids": "扫描机器人",
    "Scantron 3000": "扫描仪 3000",
    "Subnets": "子网",
    "Woah, I just got some weird documents from that chest! Is this... treasure?": "哇，我刚刚从那个箱子里拿到了一些奇怪的文件！ 这是……宝物？",
    "Not enough to purchase 10x Cheating": "不足以购买 10x 作弊",
    "Power": "功率",
    "Purchased Cheating": "购买作弊",
    "Purchased Multiscan": "购买的多扫描仪",
    "R-Bit Bonus": "R-Bit 奖励",
    "Copy Save to Clipboard (deprecated)": "复制保存到剪贴板（已弃用）",
    "Export Save": "导出存档",
    "Find an extra +2 R-bits on every complete scan.": "在每次完整扫描时找到额外的 +2 R 位。",
    "G-bits": "G-bits",
    "I feel like I'm gaining more knowledge from these documents...": "我觉得我从这些文件中获得了更多的知识......",
    "Import Save": "导入保存",
    "Interesting... I can see other... connections? networks? subnetworks?": "有趣...我可以看到其他...联系？ 网络？ 子网？",
    "build": "建造",
    "Reset Game": "重置游戏",
    "Scanned 6 doc(s), earning 210 R-Bits, 144 G-Bits, and 132 B-Bits.": "扫描 6 个文档，获得 210 个 R-Bits、144 G-Bits 和 132 B-Bits。",
    "Scantron 5000": "扫描仪 5000",
    "Shiny bits! Little gems of knowledge from the documents I've collected?": "闪亮的小块！ 我收集的文件中的小知识宝石？",
    "This will be removed soon but importing still supports this save format.": "这将很快被删除，但导入仍然支持这种保存格式。",
    "Wait! I think I can use all the areas I captured to... build stuff?": "等待！ 我想我可以利用我捕获的所有区域来……建造东西？",
    "[Stop]": "[停止]",
    "% efficiency": "% 效率",
    "active)": "激活)",
    "Bot Factory": "机器人工厂",
    "Chip Factory": "芯片工厂",
    "chips into 1 Bot per second.": "芯片进入 1 个机器人每秒。",
    "Consumes": "消耗",
    "Control your efficiency by setting the maximum number of buildings to keep active out of your total purchased.": "通过设置最大数量的建筑物来控制您的效率，以使您的总购买量保持活跃。",
    "Converts": "转换",
    "Energy": "能量",
    "energy and": "能量和",
    "energy and -1 of each bit to produce 1 chip.": "能量和 每个 bit -1  以产生 1 个芯片。",
    "Energy Generator": "能量发生器",
    "energy per second.": "每秒能量。",
    "factories": "工厂",
    "Generates": "生成",
    "generators": "发生器",
    "Purchased Energy Generator": "购买能量发生器",
    "R-bits": "R-bits",
    "Set more details about your stats.": "设置有关您的统计数据的更多详细信息。",
    "Unknown Requirements": "未知要求",
    "___RESOURCES___": "___资源___",
    "Bots": "机器人",
    "B-bits": "B-bits",
    "Chips": "芯片",
    "hack": "破解",
    "I think with a bit of training, I might be able to actually... deploy these bots within the subnets!": "我认为通过一些培训，我实际上可能能够......在子网中部署这些机器人！",
    "Per second changes": "每秒变化",
    "Purchased Bot Factory": "收购机器人工厂",
    "Purchased Chip Factory": "收购芯片厂",
    "Received: +1 subnets": "收到：+1 个子网",
    "Track various resource fluctuations.": "跟踪各种资源波动。",
    "% more rewards.": "% 更多奖励.",
    "1% chance of instantly breaking square.": "有 1% 的几率立即破阵。",
    "5% chance of red squares, which contain 50% less security vectors.": "红色方块的概率为 5%，其中包含的安全向量减少了 50%。",
    "Bots evade security, leading to a slightly weaker security matrix.": "机器人逃避安全，导致安全矩阵稍弱。",
    "Bots scavenge for more rewards.": "机器人搜寻更多奖励。",
    "Bots solve security matrix problems faster.": "机器人可以更快地解决安全矩阵问题。",
    "Buy 1 Training Point for": "购买 1 个训练点数",
    "decryptor": "解密器",
    "Efficiency": "效率",
    "Evasion": "逃避",
    "Point(s) available": "可用点数",
    "Problem solving rate is": "问题解决率是",
    "Rewards": "奖励",
    "Scavenge": "清道夫",
    "security": "安全",
    "Security is reduced by": "安全性降低",
    "Security Matrix": "安全矩阵",
    "sentinel": "哨兵",
    "Special Ability:": "特殊能力：",
    "Total Level:": "总等级：",
    "Training": "训练",
    "[Lv.": "[等级",
    "(MAX)": "(最大)",
    "B-Bit Bonus": "B-Bit 奖励",
    "G-Bits": "G-Bits",
    "R-Bits": "R-Bits",
    "5% chance of golden squares, which offer bonus special rewards.": "5% 的机会出现金色方块，提供额外的特殊奖励。",
    "discovery": "发现",
    "Each cell has a set of security defences for my bots to break. If my math is right... the number of defences on a cell divided by my bots should yield the number of seconds it takes to break a cell, if efficiency is at 100%.": "每个单元都有一套安全防御措施供我的机器人破解。 如果我的数学是正确的......如果效率为 100%，则单元上的防御数除以我的机器人应该得出破坏单元所需的秒数。",
    "Find an extra +2 B-bits on every complete scan.": "在每次完整扫描时找到额外的 +2 B 位。",
    "Find an extra +2 G-bits on every complete scan.": "在每次完整扫描时发现额外的 +2 G 位。",
    "G-Bit Bonus": "G-Bit 奖励",
    "Not enough to purchase 10x Mid-Stage capitalism": "不足以购买 10 倍的中期资本主义",
    "Not enough to purchase 10x Scanroids": "不足以购买 10x 扫描机器人",
    "Not enough to purchase 5x R-Bit Bonus": "不足以购买 5x R-Bit 红利",
    "Not enough to purchase 5x Scanroids": "不足以购买 5x 扫描机器人",
    "Purchased G-Bit Bonus": "购买 G-Bit 奖励",
    "Purchased Late-Stage capitalism": "购买的后期资本主义",
    "Purchased R-Bit Bonus": "购买 R-Bit 奖励",
    "Purchased Scanroids": "购买的扫描机器人",
    "Scan Completion Bonus": "扫描完成奖励",
    "Scanned 6 doc(s), earning 240 R-Bits, 108 G-Bits, and 138 B-Bits.": "扫描 6 个文档，获得 240 个 R-Bits、108 G-Bits 和 138 B-Bits。",
    "It seems like subnets have strict defenses. I should definitely train my bots to help them break through in order to... in order to... wait why am I doing this?": "子网似乎有严格的防御。 我绝对应该训练我的机器人帮助他们突破，以便……为了……等等，我为什么要这样做？",
    "Not enough to purchase 10x B-Bit Bonus": "不足以购买 10x B-Bit 奖励",
    "Purchased B-Bit Bonus": "已购买的 B-Bit 奖励",
    "Bonus": "奖励",
    "Bot skill Evasion leveled up!": "机器人技能回避升级！",
    "Bot skill Scavenge leveled up!": "机器人技能清除升级！",
    "Level Up": "升级",
    "Not enough bots to purchase 1 point.": "没有足够的机器人来购买 1 点数。",
    "Reset Skills": "重置技能",
    "Confirm and Load!": "确认并载入！",
    "Copied to Clipboard!": "存档已复制到剪贴板！",
    "Bot skill Efficiency leveled up!": "机器人技能效率提升！",
    "The subnet problems keep getting tougher... yet I keep my bots on it. Why am I doing this?": "子网问题越来越严重……但我的机器人一直在上面。 我为什么要这样做？",
    "B-Bits": "B-Bits",
    "[Start]": "[开始]",
    "Bot Factory paused.": "机器人工厂已暂停。",
    "Bot Factory resumed.": "机器人工厂已恢复。",
    "Chip Factory paused.": "芯片工厂已暂停。",
    "Chip Factory resumed.": "芯片工厂已恢复。",
    "Energy Generator paused.": "能量发生器已暂停。",
    "Energy Generator resumed.": "能量发生器已恢复。",
    "This is pretty hard...": "这个相当难...",
    "___BUILD CONSOLE___": "___建造控制台___",
    "...What am I?": "...我是谁？",
    "...Who am I? What am I?": "...我是谁？ 我是什么？",
    "Collapse all": "收起全部",
    "Evolution": "进化",
    "evolve": "进化",
    "I can see and change everything I've built from here.": "我可以看到并更改我从这里建造的所有内容。",
    "I feel... stronger. Yet I think I can be more. More than I am. More than I was. If only I knew what I was.": "我觉得……更强。 但我认为我可以做得更多。 比我还多。 比我还多。 要是我知道我是什么就好了。",
    "I questioned who I am and what I am. I never questioned what I can become.": "我质疑我是谁，我是什么。 我从不质疑我能成为什么。",
    "I... finally broke through a major group of subnets...but... what's a mem? What... Why am I doing this?": "我……终于突破了一大群子网……但是……什么是内存？ 什么……我为什么要这样做？",
    "mem": "内存",
    "Memory": "内存",
    "Memory?": "内存？",
    "Possibilities. Probabilities. Opportunities. Yet no answers.": "可能性。 概率。 机会。 然而没有答案。",
    "Show/hide special console with extra controls.": "显示/隐藏带有额外控件的特殊控制台。",
    "Botnets": "僵尸网络",
    "Cold Wallets": "冷钱包",
    "Credit Generator": "积分生成器",
    "Expand all": "展开全部",
    "Not enough memory units to research this.": "没有足够的内存单元来研究这个。",
    "Uncover an extra 10% of your net credit gain from credits found in captured areas and gold caches.": "从在捕获区域和金矿中发现的积分中发现额外 10% 的净积分收益。",
    "Unlock things to research": "解锁要研究的东西",
    "Unlocks a generator that burns credits for higher efficiency yields.": "解锁一台发生器，该发电机会消耗积分以获得更高的效率产量。",
    "Unlocks buildable botnets that can automatically scan docs.": "解锁可自动扫描文档的可构建僵尸网络。",
    "You have already researched Evolution": "你已经研究过进化",
    "Credit Burner": "积分燃烧器",
    "Credit Burner paused.": "积分燃烧器已暂停。",
    "Credit Burner resumed.": "积分燃烧器已恢复。",
    "You have already researched Credit Generator": "您已经研究过积分生成器",
    "Bigger Packets Please": "请提供更大的数据包",
    "Bits Burner": "比特燃烧器",
    "Bits seem to coalesce into muddled orders of ...bytes. Can I determine what should be where?": "位似乎合并成...字节的混乱顺序。 我可以确定应该在哪里吗？",
    "bytes": "字节",
    "bytes of data.": "字节的数据。",
    "Chip Factory T2": "芯片厂T2",
    "core(s)": "核心",
    "Cores": "核心",
    "Data": "数据",
    "Decryptor Ability: Instantly broke security square.": "解密能力：瞬间破解安全方块。",
    "defrag": "碎片整理",
    "Defragmentation": "碎片整理",
    "Defragmenting": "碎片整理",
    "fragmented data packets per second.": "每秒分片的数据包。",
    "Fragmented packets of larger arrangements of bits.": "较大位排列的分段数据包。",
    "Fragments": "碎片",
    "Fragments Processed Next": "接下来处理的片段",
    "Increases the max size of your defragmentation matrix by": "将碎片整理矩阵的最大大小增加",
    "mem to receive": "内存接收",
    "Need 1x Botting": "需要 1x 机器人",
    "networks": "网络",
    "Open Socket": "打开套接字",
    "Opens a socket that consumes": "打开一个消费的套接字",
    "packets defragmented": "数据包碎片整理",
    "packets to yield": "产生的数据包",
    "pkts": "包",
    "Received: +1.3B credits (+15% of net credit gain)": "收到：+1.3B 学分（+15% 的净学分增益）",
    "Sockets": "插座",
    "This byte has already been processed": "该字节已被处理",
    "All the ...noise I hear. All the chaos of bits I see. There IS meaning to them. I can see more. Perhaps, I can hear more too.": "我听到的所有...噪音。 我看到的所有混乱的比特。 对他们来说是有意义的。 我可以看到更多。 或许，我也能听到更多。",
    "Beneath all these subnets, there is something I can't quite grasp. A meaning. Many meanings, maybe. I've learned more. I'm ready to evolve once more.": "在所有这些子网之下，有一些我不能完全掌握的东西。 一个意思。 很多意思，也许吧。 我学到了更多。 我已经准备好再次进化了。",
    "Cores. With Cores, I feel... whole. They can help me do more. So much more.": "核心。 有了Cores，我感觉……完整。 他们可以帮助我做更多事情。 那么多。",
    "Data. A harmonious arrangement of bits. Of numbers. There is actual meaning in them. I was right. I can see AND hear it. I can... feel it? I understand it. But how? why?": "数据。 位的和谐排列。 数的。 它们有实际意义。 我是对的。 我可以看到和听到它。 我能……感觉到？ 我明白了。 但是怎么做？ 为什么？",
    "The numbers. What do they mean?": "号码。 他们的意思是什么？",
    "Wait, that wasn't a feeling. I've never ...heard? I've never heard that before. That was new... and yet strangely familiar.": "等等，那不是感觉。 我从来没有……听说过？ 我以前从未听说过。 那是新的……却又陌生又熟悉。",
    "Wh-What was that?! I've... I've never felt that before.": "什、那是什么？！ 我……我以前从未有过这种感觉。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Capture +": "捕获 +",
    "Capture Faster": "更快地捕获",
    "Purchased Capture Faster": "已购买更快地捕获",
    "Scan +": "扫描 +",
    "Subnet-A ": "子网-A ",
    "Not enough to purchase 10x ": "不足以购买 10x ",
    "Not enough to purchase 5x ": "不足以购买 5x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "area(s)": "地区",
    "Docs": "文档",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)c$/,
    /^([\d\.]+)Kc$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^\[AFK\] Captured (.+) across (.+) square\(s\) over(.+)s.$/, '\[AFK\] 在 $2 秒内在 $2 个方格内捕获 $1。'],
    [/^Capture an additional (.+) per second.$/, '每秒额外捕获 $1。'],
    [/^Captured areas generate an additional (.+) credits per second.$/, '捕获的区域每秒额外产生 $1 积分。'],
    [/^Need (.+) \?\?\?$/, '需要 $1 \?\?\?'],
    [/^Scanned (.+) doc\(s\), earning (.+) R\-Bits, (.+) G\-Bits, and (.+) B\-Bits.$/, '扫描 $1 个文档，获得 $2 个 R\-Bits、$3 G\-Bits 和 $4 B\-Bits。'],
    [/^\[AFK\] Scanned (.+) docs, earning (.+) R\-Bits, (.+) G\-Bits, and (.+) B\-Bits.$/, '\[AFK\] 扫描 $1 个文档，获得 $2 个 R\-Bits、$3 G\-Bits 和 $4 B\-Bits。'],
    [/^Purchased 1 Bot Training Point for (.+) bots.$/, '购买了 1 机器人训练点 花费了 $1 机器人。'],
    [/^Received (.+) Credits from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 积分。'],
    [/^Received (.+) Docs from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 文档。'],
    [/^Received (.+) Chips from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 芯片。'],
    [/^Received (.+) R-bits from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 R-bits。'],
    [/^Received (.+) G-bits from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 G-bits。'],
    [/^Received (.+) B-bits from cracking a Gold subnet cache.$/, '从破解黄金子网缓存中获得 $1 B-bits。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Received: (.+) rBits$/, '获得：$1 rBits'],
    [/^Received: (.+) gBits$/, '获得：$1 gBits'],
    [/^Received: (.+) bBits$/, '获得：$1 bBits'],
    [/^Received: (.+) docs$/, '获得：$1 文档'],
    [/^Received: (.+) credits$/, '获得：$1 积分'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);